version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: app
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    build: .docker/postgres
    container_name: db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/db:/var/lib/postgresql/data
    env_file:
      - .env
